version: 0.0
os: linux
files:
   - source: /Index.html
     destination: /usr/share/nginx/html/Login
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
